kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: custom_clone
    image: plugins/git
    settings:
      depth: 10
      skip_verify: true

  - name: tests
    image: node:latest
    commands:
      - npm install
      - npm test

  - name: eslint
    image: node:latest
    commands:
      - npm install -g --force eslint
      - eslint --fix ./

  - name: codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
