kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: tests
    commands:
      - yarn test

  - name: eslint
    commands:
      - eslint --fix ./

  - name: codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
